[package]
name = "Rabies"
version = "0.1.0"
edition = "2021"

[dependencies]
symphonia = { version = "0.5", features = ["all"] }
parking_lot = "0.12"
eframe = "0.27"
egui = "0.27"
rfd = "0.14"
cpal = "0.15"
atomic_float = "0.1"